/*
 * YOMO-Service-Emulation with AHOI
 * [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0-yomo-emulator
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InputFieldDescription;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AccessDescription
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-05T14:43:56.054Z")
public class AccessDescription {
  @SerializedName("infoText")
  private String infoText = null;

  @SerializedName("fieldDescriptions")
  private List<InputFieldDescription> fieldDescriptions = null;

  public AccessDescription infoText(String infoText) {
    this.infoText = infoText;
    return this;
  }

   /**
   * Information text by the provider as a description for required user actions during the account setup (e.g.,  \&quot;Provided your financial institution has not given you a separate username, please enter  your account number as your username. Depending on your financial institution,  additional information such as a customer number can be entered. Most of the time  entering this information is optional.\&quot;)
   * @return infoText
  **/
  @ApiModelProperty(value = "Information text by the provider as a description for required user actions during the account setup (e.g.,  \"Provided your financial institution has not given you a separate username, please enter  your account number as your username. Depending on your financial institution,  additional information such as a customer number can be entered. Most of the time  entering this information is optional.\")")
  public String getInfoText() {
    return infoText;
  }

  public void setInfoText(String infoText) {
    this.infoText = infoText;
  }

  public AccessDescription fieldDescriptions(List<InputFieldDescription> fieldDescriptions) {
    this.fieldDescriptions = fieldDescriptions;
    return this;
  }

  public AccessDescription addFieldDescriptionsItem(InputFieldDescription fieldDescriptionsItem) {
    if (this.fieldDescriptions == null) {
      this.fieldDescriptions = new ArrayList<InputFieldDescription>();
    }
    this.fieldDescriptions.add(fieldDescriptionsItem);
    return this;
  }

   /**
   * Information to describe and facilitate validation of an access.
   * @return fieldDescriptions
  **/
  @ApiModelProperty(value = "Information to describe and facilitate validation of an access.")
  public List<InputFieldDescription> getFieldDescriptions() {
    return fieldDescriptions;
  }

  public void setFieldDescriptions(List<InputFieldDescription> fieldDescriptions) {
    this.fieldDescriptions = fieldDescriptions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessDescription accessDescription = (AccessDescription) o;
    return Objects.equals(this.infoText, accessDescription.infoText) &&
        Objects.equals(this.fieldDescriptions, accessDescription.fieldDescriptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(infoText, fieldDescriptions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessDescription {\n");
    
    sb.append("    infoText: ").append(toIndentedString(infoText)).append("\n");
    sb.append("    fieldDescriptions: ").append(toIndentedString(fieldDescriptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

