/*
 * YOMO-Service-Emulation with AHOI
 * [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0-yomo-emulator
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Account;
import io.swagger.client.model.Balance;
import java.io.IOException;

/**
 * BankAccount
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-05T14:43:56.054Z")
public class BankAccount extends Account {
  @SerializedName("number")
  private String number = null;

  @SerializedName("bankCodeNumber")
  private String bankCodeNumber = null;

  @SerializedName("bic")
  private String bic = null;

  @SerializedName("iban")
  private String iban = null;

  @SerializedName("currency")
  private String currency = null;

  @SerializedName("balance")
  private Balance balance = null;

  public BankAccount number(String number) {
    this.number = number;
    return this;
  }

   /**
   * Account number (national)
   * @return number
  **/
  @ApiModelProperty(required = true, value = "Account number (national)")
  public String getNumber() {
    return number;
  }

  public void setNumber(String number) {
    this.number = number;
  }

  public BankAccount bankCodeNumber(String bankCodeNumber) {
    this.bankCodeNumber = bankCodeNumber;
    return this;
  }

   /**
   * Bank code number (BLZ, national, 8 digits)
   * @return bankCodeNumber
  **/
  @ApiModelProperty(required = true, value = "Bank code number (BLZ, national, 8 digits)")
  public String getBankCodeNumber() {
    return bankCodeNumber;
  }

  public void setBankCodeNumber(String bankCodeNumber) {
    this.bankCodeNumber = bankCodeNumber;
  }

  public BankAccount bic(String bic) {
    this.bic = bic;
    return this;
  }

   /**
   * Business Identifier Code (BIC; ISO 9362)
   * @return bic
  **/
  @ApiModelProperty(required = true, value = "Business Identifier Code (BIC; ISO 9362)")
  public String getBic() {
    return bic;
  }

  public void setBic(String bic) {
    this.bic = bic;
  }

  public BankAccount iban(String iban) {
    this.iban = iban;
    return this;
  }

   /**
   * International Bank Account Number (IBAN; ISO 13616-1)
   * @return iban
  **/
  @ApiModelProperty(required = true, value = "International Bank Account Number (IBAN; ISO 13616-1)")
  public String getIban() {
    return iban;
  }

  public void setIban(String iban) {
    this.iban = iban;
  }

  public BankAccount currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Account currency (ISO 4217) (e.g., \&quot;EUR\&quot;)
   * @return currency
  **/
  @ApiModelProperty(required = true, value = "Account currency (ISO 4217) (e.g., \"EUR\")")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public BankAccount balance(Balance balance) {
    this.balance = balance;
    return this;
  }

   /**
   * Current balance. This value is set whenever the account is refreshed.
   * @return balance
  **/
  @ApiModelProperty(required = true, value = "Current balance. This value is set whenever the account is refreshed.")
  public Balance getBalance() {
    return balance;
  }

  public void setBalance(Balance balance) {
    this.balance = balance;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankAccount bankAccount = (BankAccount) o;
    return Objects.equals(this.number, bankAccount.number) &&
        Objects.equals(this.bankCodeNumber, bankAccount.bankCodeNumber) &&
        Objects.equals(this.bic, bankAccount.bic) &&
        Objects.equals(this.iban, bankAccount.iban) &&
        Objects.equals(this.currency, bankAccount.currency) &&
        Objects.equals(this.balance, bankAccount.balance) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(number, bankCodeNumber, bic, iban, currency, balance, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankAccount {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    bankCodeNumber: ").append(toIndentedString(bankCodeNumber)).append("\n");
    sb.append("    bic: ").append(toIndentedString(bic)).append("\n");
    sb.append("    iban: ").append(toIndentedString(iban)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

