/*
 * YOMO-Service-Emulation with AHOI
 * [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0-yomo-emulator
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AccessDescription;
import io.swagger.client.model.Provider;
import java.io.IOException;

/**
 * BankProvider
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-05T14:43:56.054Z")
public class BankProvider extends Provider {
  @SerializedName("bankCode")
  private String bankCode = null;

  @SerializedName("bic")
  private String bic = null;

  public BankProvider bankCode(String bankCode) {
    this.bankCode = bankCode;
    return this;
  }

   /**
   * Bank code number (BLZ, national, 8 digits)
   * @return bankCode
  **/
  @ApiModelProperty(required = true, value = "Bank code number (BLZ, national, 8 digits)")
  public String getBankCode() {
    return bankCode;
  }

  public void setBankCode(String bankCode) {
    this.bankCode = bankCode;
  }

  public BankProvider bic(String bic) {
    this.bic = bic;
    return this;
  }

   /**
   * Business Identifier Code (defined in ISO-9362)
   * @return bic
  **/
  @ApiModelProperty(required = true, value = "Business Identifier Code (defined in ISO-9362)")
  public String getBic() {
    return bic;
  }

  public void setBic(String bic) {
    this.bic = bic;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankProvider bankProvider = (BankProvider) o;
    return Objects.equals(this.bankCode, bankProvider.bankCode) &&
        Objects.equals(this.bic, bankProvider.bic) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bankCode, bic, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankProvider {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    bankCode: ").append(toIndentedString(bankCode)).append("\n");
    sb.append("    bic: ").append(toIndentedString(bic)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

