/*
 * YOMO-Service-Emulation with AHOI
 * [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0-yomo-emulator
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SelfDescribedValue
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-05T14:43:56.054Z")
public class SelfDescribedValue {
  @SerializedName("value")
  private String value = null;

  @SerializedName("specification")
  private String specification = null;

  public SelfDescribedValue value(String value) {
    this.value = value;
    return this;
  }

   /**
   * api.dto.model.com-starfinanz-ahoi-dto-v2-SelfDescribedValueDto.properties.value.description
   * @return value
  **/
  @ApiModelProperty(required = true, value = "api.dto.model.com-starfinanz-ahoi-dto-v2-SelfDescribedValueDto.properties.value.description")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public SelfDescribedValue specification(String specification) {
    this.specification = specification;
    return this;
  }

   /**
   * api.dto.model.com-starfinanz-ahoi-dto-v2-SelfDescribedValueDto.properties.specification.description
   * @return specification
  **/
  @ApiModelProperty(required = true, value = "api.dto.model.com-starfinanz-ahoi-dto-v2-SelfDescribedValueDto.properties.specification.description")
  public String getSpecification() {
    return specification;
  }

  public void setSpecification(String specification) {
    this.specification = specification;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SelfDescribedValue selfDescribedValue = (SelfDescribedValue) o;
    return Objects.equals(this.value, selfDescribedValue.value) &&
        Objects.equals(this.specification, selfDescribedValue.specification);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, specification);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SelfDescribedValue {\n");
    
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    specification: ").append(toIndentedString(specification)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

