/*
 * YOMO-Service-Emulation with AHOI
 * [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0-yomo-emulator
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TanMedia
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-05T14:43:56.054Z")
public class TanMedia {
  @SerializedName("tanMediaId")
  private String tanMediaId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  public TanMedia tanMediaId(String tanMediaId) {
    this.tanMediaId = tanMediaId;
    return this;
  }

   /**
   * ID of this TAN media
   * @return tanMediaId
  **/
  @ApiModelProperty(required = true, value = "ID of this TAN media")
  public String getTanMediaId() {
    return tanMediaId;
  }

  public void setTanMediaId(String tanMediaId) {
    this.tanMediaId = tanMediaId;
  }

  public TanMedia name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of TANMedia (e.g., \&quot;iTan\&quot;)
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name of TANMedia (e.g., \"iTan\")")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TanMedia description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of TANMedia (e.g., phone number or card number used for given type)
   * @return description
  **/
  @ApiModelProperty(required = true, value = "Description of TANMedia (e.g., phone number or card number used for given type)")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TanMedia tanMedia = (TanMedia) o;
    return Objects.equals(this.tanMediaId, tanMedia.tanMediaId) &&
        Objects.equals(this.name, tanMedia.name) &&
        Objects.equals(this.description, tanMedia.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tanMediaId, name, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TanMedia {\n");
    
    sb.append("    tanMediaId: ").append(toIndentedString(tanMediaId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

