/*
 * YOMO-Service-Emulation with AHOI
 * [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0-yomo-emulator
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.TanMedia;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * TanScheme
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-05T14:43:56.054Z")
public class TanScheme {
  @SerializedName("schemeId")
  private String schemeId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("tanMediaList")
  private List<TanMedia> tanMediaList = null;

  public TanScheme schemeId(String schemeId) {
    this.schemeId = schemeId;
    return this;
  }

   /**
   * Internal ID of this TAN scheme (generated value)
   * @return schemeId
  **/
  @ApiModelProperty(value = "Internal ID of this TAN scheme (generated value)")
  public String getSchemeId() {
    return schemeId;
  }

  public void setSchemeId(String schemeId) {
    this.schemeId = schemeId;
  }

  public TanScheme name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the used TAN scheme
   * @return name
  **/
  @ApiModelProperty(value = "Name of the used TAN scheme")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TanScheme tanMediaList(List<TanMedia> tanMediaList) {
    this.tanMediaList = tanMediaList;
    return this;
  }

  public TanScheme addTanMediaListItem(TanMedia tanMediaListItem) {
    if (this.tanMediaList == null) {
      this.tanMediaList = new ArrayList<TanMedia>();
    }
    this.tanMediaList.add(tanMediaListItem);
    return this;
  }

   /**
   * List of available TAN media for this scheme
   * @return tanMediaList
  **/
  @ApiModelProperty(value = "List of available TAN media for this scheme")
  public List<TanMedia> getTanMediaList() {
    return tanMediaList;
  }

  public void setTanMediaList(List<TanMedia> tanMediaList) {
    this.tanMediaList = tanMediaList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TanScheme tanScheme = (TanScheme) o;
    return Objects.equals(this.schemeId, tanScheme.schemeId) &&
        Objects.equals(this.name, tanScheme.name) &&
        Objects.equals(this.tanMediaList, tanScheme.tanMediaList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(schemeId, name, tanMediaList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TanScheme {\n");
    
    sb.append("    schemeId: ").append(toIndentedString(schemeId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    tanMediaList: ").append(toIndentedString(tanMediaList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

