/*
 * YOMO-Service-Emulation with AHOI
 * [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0-yomo-emulator
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ResponseObjectMap;
import java.io.IOException;

/**
 * TransferChallengeResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-05T14:43:56.054Z")
public class TransferChallengeResponse {
  @SerializedName("transferTaskId")
  private Long transferTaskId = null;

  @SerializedName("responseObjects")
  private ResponseObjectMap responseObjects = null;

  public TransferChallengeResponse transferTaskId(Long transferTaskId) {
    this.transferTaskId = transferTaskId;
    return this;
  }

   /**
   * TransferTaskID — The referenced task for that payment challenge
   * @return transferTaskId
  **/
  @ApiModelProperty(value = "TransferTaskID — The referenced task for that payment challenge")
  public Long getTransferTaskId() {
    return transferTaskId;
  }

  public void setTransferTaskId(Long transferTaskId) {
    this.transferTaskId = transferTaskId;
  }

  public TransferChallengeResponse responseObjects(ResponseObjectMap responseObjects) {
    this.responseObjects = responseObjects;
    return this;
  }

   /**
   * FieldSet — The required InputFields for that challenge
   * @return responseObjects
  **/
  @ApiModelProperty(required = true, value = "FieldSet — The required InputFields for that challenge")
  public ResponseObjectMap getResponseObjects() {
    return responseObjects;
  }

  public void setResponseObjects(ResponseObjectMap responseObjects) {
    this.responseObjects = responseObjects;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransferChallengeResponse transferChallengeResponse = (TransferChallengeResponse) o;
    return Objects.equals(this.transferTaskId, transferChallengeResponse.transferTaskId) &&
        Objects.equals(this.responseObjects, transferChallengeResponse.responseObjects);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transferTaskId, responseObjects);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransferChallengeResponse {\n");
    
    sb.append("    transferTaskId: ").append(toIndentedString(transferTaskId)).append("\n");
    sb.append("    responseObjects: ").append(toIndentedString(responseObjects)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

