/*
 * YOMO-Service-Emulation with AHOI
 * [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0-yomo-emulator
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Provider;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProviderApi
 */
@Ignore
public class ProviderApiTest {

    private final ProviderApi api = new ProviderApi();

    
    /**
     * Get provider
     *
     * Retrieve a single provider identified by **providerId**.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProviderTest() throws ApiException {
        Long providerId = null;
        Provider response = api.getProvider(providerId);

        // TODO: test validations
    }
    
    /**
     * List bank providers
     *
     * Retrieve a list of bank providers. A provider-**id** is necessary to create an _access_. To retrieve the necessary access fields, you need to query the specific &#x60;provider/{providerId}&#x60;. For performance reasons they are kept separate. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProvidersTest() throws ApiException {
        String bankCode = null;
        Boolean supported = null;
        String query = null;
        List<Provider> response = api.getProviders(bankCode, supported, query);

        // TODO: test validations
    }
    
}
