/*
 * YOMO-Service-Emulation with AHOI
 * [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0-yomo-emulator
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.TanMedia;
import io.swagger.client.model.TanScheme;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TANSchemesApi
 */
@Ignore
public class TANSchemesApiTest {

    private final TANSchemesApi api = new TANSchemesApi();

    
    /**
     * Get current TAN media.
     *
     * Returns the currently selected TAN media for the access.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCurrentTanMediaTest() throws ApiException {
        Long accessId = null;
        TanMedia response = api.getCurrentTanMedia(accessId);

        // TODO: test validations
    }
    
    /**
     * Get current TAN scheme.
     *
     * Returns the currently selected TAN scheme for the access.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCurrentTanSchemeTest() throws ApiException {
        Long accessId = null;
        TanScheme response = api.getCurrentTanScheme(accessId);

        // TODO: test validations
    }
    
    /**
     * List TAN schemes for access
     *
     * Retrieves all available TAN schemes for access.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTanSchemesTest() throws ApiException {
        Long accessId = null;
        Long maxAge = null;
        List<TanScheme> response = api.getTanSchemes(accessId, maxAge);

        // TODO: test validations
    }
    
}
